var checkIsValid=function(a){if(!a||"string"!==typeof a)return!1;var c=a.split(".");if(5>c.length)return!1;const b=c[1],e=c[2],d=c[3];c=c[4];return!a.startsWith("W1")||Number.isNaN(Number(b))||Number.isNaN(Number(e))||!/^[a-zA-Z0-9_-]{21}$/.test(d)||Number.isNaN(Number(c))||Number(c)>(new Date).getTime()?!1:!0},checkCookieWritable=function(a){try{document.cookie="cookietest=1"+(a?"; domain="+a:"");var c=-1!=document.cookie.indexOf("cookietest=");document.cookie="cookietest=1; expires=Thu, 01-Jan-1970 00:00:01 GMT"+
(a?"; domain="+a:"");return c}catch(b){return!1}},cookie={write:function(a,c,b,e,d){var f=new Date;b=b||730;d=d||"/";f.setTime(f.getTime()+864E5*b);b="; expires="+f.toGMTString();a=a+"="+c+b+"; path="+d;e&&(a+="; domain="+e);document.cookie=a},read:function(a){var c="";(""+document.cookie).split(" ").forEach(b=>{[,b]=b.split(`${a}=`);b&&(c=";"===b[b.length-1]?b.slice(0,b.length-1):b)});return c},readAll:function(a){return""+document.cookie},remove:function(a){this.read(a)&&this.write(a,"",-1,"/")}};
function ready(a){"loading"!=document.readyState?a():window.addEventListener?window.addEventListener("DOMContentLoaded",a):window.attachEvent("onreadystatechange",function(){"loading"!=document.readyState&&a()})}
function getDevice(){var a=navigator.userAgent,c=navigator.appName,b=""+parseFloat(navigator.appVersion);parseInt(navigator.appVersion,10);var e,d,f;-1!=(d=a.indexOf("OPR"))?(c="Opera",b=a.substring(d+4),-1!=(d=a.indexOf("Version"))&&(b=a.substring(d+8))):-1!=(d=a.indexOf("Edg"))?(c="Microsoft Edge",b=a.substring(d+4)):-1!=(d=a.indexOf("MSIE"))?(c="Microsoft Internet Explorer",b=a.substring(d+5)):-1!=(d=a.indexOf("Chrome"))?(c="Chrome",b=a.substring(d+7)):-1!=(d=a.indexOf("Safari"))?(c="Safari",b=
a.substring(d+7),-1!=(d=a.indexOf("Version"))&&(b=a.substring(d+8))):-1!=(d=a.indexOf("Firefox"))?(c="Firefox",b=a.substring(d+8)):(e=a.lastIndexOf(" ")+1)<(d=a.lastIndexOf("/"))&&(c=a.substring(e,d),b=a.substring(d+1),c.toLowerCase()==c.toUpperCase()&&(c=navigator.appName));-1!=(f=b.indexOf(";"))&&(b=b.substring(0,f));-1!=(f=b.indexOf(" "))&&(b=b.substring(0,f));a=parseInt(""+b,10);isNaN(a)&&(b=""+parseFloat(navigator.appVersion),a=parseInt(navigator.appVersion,10));return{browserName:c,fullVersion:b,
majorVersion:a,appName:navigator.appName}}function getOS(){var a="Unknown OS";-1!=navigator.appVersion.indexOf("Win")&&(a="Windows");-1!=navigator.appVersion.indexOf("Mac")&&(a="MacOS");-1!=navigator.appVersion.indexOf("X11")&&(a="UNIX");-1!=navigator.appVersion.indexOf("Linux")&&(a="Linux");return a}function getGUID(){var a=window.navigator,c=window.screen,b=a.mimeTypes.length;b+=a.userAgent.replace(/\D+/g,"");b+=a.plugins.length;b+=c.height||"";b+=c.width||"";return b+=c.pixelDepth||""}
function getNanoID(a=21){return crypto.getRandomValues(new Uint8Array(a)).reduce((c,b)=>c+(36>(b&=63)?b.toString(36):62>b?(b-26).toString(36).toUpperCase():62<b?"-":"_"),"")}
function init(){if(!checkIsValid(cookie.read("__w_id"))){let a=getDevice();const c={wrtn_id:`W1.${window.location.origin.split(".").length}.${getGUID()}.${getNanoID()}.${Date.now()}`,cookie_raw:cookie.readAll(),page_path:window.location.pathname,user_agent:window.navigator.userAgent,os_name:getOS(),browser_name:a.browserName,browser_version:a.fullVersion,app_name:a.appName,referrer:window.location.href,lang:window.navigator.language};fetch("https://api.wow.wrtn.ai/meta",{method:"post",headers:{"Content-Type":"application/json"},
body:JSON.stringify(c)}).then(b=>{b=window.location.hostname.includes("localhost")?"localhost":"."+window.location.hostname.split(".").map(e=>e.replace(".","")).slice(-2).join(".");cookie.write("__w_id",c.wrtn_id,void 0,b)}).catch(b=>{})}}init();
